#!/usr/bin/env python3

import argparse
import sys

_LAMMPS_VARIABLES = {}
_LAMMPS_ATOM_STYLE = {}
_LAMMPS_SYSTEM = {}
_LAMMPS_FORCEFIELD = {}
_LAMMPS_FIXES = {}

_LAMMPS_BLOCKS = [
    _LAMMPS_VARIABLES,
    _LAMMPS_ATOM_STYLE,
    _LAMMPS_SYSTEM,
    _LAMMPS_FORCEFIELD,
    _LAMMPS_FIXES,
]

_INPUT_ESSENTIALS = [
    "header",
    "inputs",
    "type",
    "ens_var",
    "output",
    "footer",
    "pbc",
    "coord",
]

_MD_ESSENTIALS = [
    "md_var",
    "random",
    "ensemble",
    "dump",
    "thermo_output",
    "dump",
]

_INPUT_METHODS = {
    "all": _INPUT_ESSENTIALS
    + _MD_ESSENTIALS
    + ["single", "minimise", "md", "deform", "plumed", "fep", "ti"],
    "single": [*_INPUT_ESSENTIALS, "single"],
    "minimise": [*_INPUT_ESSENTIALS, "minimise"],
    "md": _INPUT_ESSENTIALS + _MD_ESSENTIALS + ["md"],
    "deform": _INPUT_ESSENTIALS + _MD_ESSENTIALS + ["md", "deform"],
    "plumed": _INPUT_ESSENTIALS + _MD_ESSENTIALS + ["md", "plumed", "task_farming"],
    "fep": _INPUT_ESSENTIALS + _MD_ESSENTIALS + ["fep", "task_farming"],
    "ti": _INPUT_ESSENTIALS + _MD_ESSENTIALS + ["ti"],
}

##############################################################################################################
_LAMMPS_VARIABLES[
    "header"
] = """# LAMMPS input file
# This file was generated by lmpgen.py script.
# It contains variable definitions and settings for a LAMMPS simulation.
# You can modify the values of the variables below to customize your simulation.
#
# ------ Units -------------------------------------
units metal                                                 # eV, ps, Angstrom, bar

# ------ Misc variables ----------------------------
variable iseed           index   -1                         # Set for reproducibility
variable timer           index   no
variable tmax            index   11:55:00
"""
_LAMMPS_VARIABLES[
    "inputs"
] = """
# ------ Simulation files --------------------------
variable ff_file         index   tersoff_refit_w2c.lmp      # force field file
variable coord_file      index   coord.lmp                  # coordinates file
variable runID           index   0                          # run ID (also for final restart)
variable rstID           index   -1                         # ID of previous restart file
variable traj_file       index   trajectory.${runID}        # trajectory file - no extension
variable old_restart     index   restart.${rstID}           # previous restart file
variable new_restart     index   restart.${runID}           # current restart file
"""
_LAMMPS_VARIABLES[
    "type"
] = """
# ------ Simulation type ---------------------------
variable single          index   no                         # single point calculation
variable minimise        index   no                         # energy minimise
variable md              index   no                         # molecular dynamics
variable deform          index   no                         # cell deformation at constant speed
variable plumed          index   no                         # PLUMED: metadynamics, etc
variable fep             index   no                         # free energy perturbation
variable ti              index   no                         # thermodynamic integration
"""
_LAMMPS_VARIABLES[
    "minimise"
] = """
# ------ Energy minimisation -------------------
variable relax_cell      index   no                         # energy minimise with variable cell
variable etol            index   1e-6                       # energy change threshold
variable ftol            index   1e-6                       # force change threshold
variable maxiter         index   100000                     # max number of iterations
"""
_LAMMPS_VARIABLES[
    "md_var"
] = """
# ------ Molecular dynamics variables -------------
variable ens             index   nvt                        # ensemble (nve, nph, nvt, npt)
variable timestep        index   0.001                      # simulation timestep (time units)
variable nsteps          index   100000                     # number of MD steps
variable nequil          index   0                          # equilibration steps - FEP only
"""
_LAMMPS_VARIABLES[
    "ens_var"
] = """
# ------ Thermostat --------------------------------
variable tst             index   csvr                       # thermostat (nh, ber, lang, csvr)
variable temp            index   300                        # global temperature (K)
variable tstart          index   ${temp}                    # starting temperature (K)
variable tfinal          index   ${temp}                    # final temperature (K)
variable trel            index   0.1                        # thermostat parameter (time units)

# ------ Barostat (NPT runs only) ------------------
variable npttype         index   iso                        # type of NPT (iso, aniso, tri, z...)
variable pres            index   1000                       # pressure bar/atm
variable prel            index   1.                         # barostat parameter (time units)
variable pdrag           index   0.0                        # barostat drag (0.0 = no drag)
"""
_LAMMPS_VARIABLES[
    "output"
] = """
# ------ Output ------------------------------------
variable nthermo         index   1000                       # thermodynamic data output frequency
variable ntraj           index   1000                       # trajectory output frequency
variable trajType        index   dcd                        # trajectory type (dcd, xtc, xyz)
"""
_LAMMPS_VARIABLES[
    "deform"
] = """
# ------ Cell deform variables ---------------------
variable def_dir         index   z                          # Direction (x, y, z, xy, yz or xz)
variable def_rate        index   -0.001                     # deformation rate
variable def_nsteps      index   100                        # change cell this many steps
"""
_LAMMPS_VARIABLES[
    "plumed"
] = """
# ------ PLUMED variables --------------------------
variable plumed_infile   index   "../plumed.inp"
variable plumed_dir      index   "Walker_"
variable nwalkers        index   32
"""
_LAMMPS_VARIABLES[
    "fep"
] = """
# ------ FEP variables -----------------------------
variable fep_file        index   "fep.inp"
variable fep_dir         index   "./"
variable fep_stages      index   20
variable gewald          index   0.3
"""
_LAMMPS_VARIABLES[
    "ti"
] = """
# ------ TI variables ------------------------------
variable ti_kappa        index   1.5
variable ti_function     index   2
"""
_LAMMPS_VARIABLES[
    "footer"
] = """
# --------------------------------------------------
# ------ UNDER THE HOOD SECTION --------------------
# --------------------------------------------------
# ------ Timer -------------------------------------
# Cleanly stops simulation after the set elapsed time
if "${timer} != no" then &
    "timer timeout ${tmax} every 1000"
"""

##############################################################################################################
_LAMMPS_ATOM_STYLE[
    "full"
] = """
# ------ Atom Style --------------------------------
atom_style full
atom_modify map array
"""
_LAMMPS_ATOM_STYLE[
    "atomic"
] = """
# ------ Atom Style --------------------------------
atom_style atomic
atom_modify map array
"""

##############################################################################################################
_LAMMPS_SYSTEM[
    "pbc"
] = """
# ------ Period Boundary Conditions ----------------
boundary p p p                                        # 3D Periodic Boundary Conditions
"""
_LAMMPS_SYSTEM[
    "coord"
] = """
# ------ Read Coordinates and Topology -------------
if "${rstID} < 0" then &
    "read_data ${coord_file}" &
else &
    "read_restart ${old_restart}"
#change_box all triclinic
"""

##############################################################################################################
_LAMMPS_FORCEFIELD[
    "full"
] = """
# ------ Read Force Field --------------------------
include ${ff_file}
"""
_LAMMPS_FORCEFIELD[
    "tersoff_wcco"
] = """
# ------ Force Field -------------------------------
# 3 atom types
variable C  equal 1
variable Co equal 2
variable W  equal 3
mass ${C}  12.011 # carbon mass (g/mole)
mass ${Co} 58.933 # cobalt mass (g/mole)
mass ${W}  183.84 # tungsten mass (g/mole)
pair_style  tersoff
pair_coeff  * * ${ff_file}  C  Co  W
"""
_LAMMPS_FORCEFIELD[
    "grace_wcco"
] = """
# ------ Force Field -------------------------------
# 3 atom types
variable C  equal 1
variable Co equal 2
variable W  equal 3
mass ${C}  12.011 # carbon mass (g/mole)
mass ${Co} 58.933 # cobalt mass (g/mole)
mass ${W}  183.84 # tungsten mass (g/mole)
pair_style  grace
pair_coeff  * * ${ff_file}  C  Co  W
"""

##############################################################################################################
_LAMMPS_FIXES[
    "random"
] = """
# ------ Random number seeds -----------------------
variable iseed          index                     -1    # Set for reproducibility
if "${iseed} <= 1" then &
    'shell "date +%s > seed.txt"' &
    'variable seed file seed.txt' &
    'shell "rm seed.txt"' &
else &
    'variable seed equal ${iseed}'
variable i0 equal round(random(1,99999,${seed}%6553))
variable i1 equal round(random(1,99999,${seed}%6553))
print "Random seed (velocities): ${i0}"
"""
_LAMMPS_FIXES[
    "task_farming"
] = """
# ------ Task Farming ------------------------------
variable nRepl equal   0
if "${fep} == yes" then "variable nRepl equal ${fep_stages}"
if "${plumed} == yes" then "variable nRepl equal ${nwalkers}"
if "${nRepl} <= 0" then "jump SELF end_farming"
    variable replID uloop ${nRepl}
    variable i0 equal ${0}+13*${replID}
    variable i1 equal ${1}+13*${replID}
    if "${fep} == yes && ${replID} < 10" then "variable dir string ${fep_dir}0${replID}"
    if "${fep} == yes && ${replID} > 9" then "variable dir string ${fep_dir}${replID}"
    if "${plumed} == yes" then "variable dir string ${plumed_dir}${replID}"
    if "${plumed} == yes || ${fep} == yes" then "shell cd ${dir}"
label end_farming
"""
_LAMMPS_FIXES[
    "restraint"
] = """
# ------ Position restraints -------------------
region restrain_region block 40 50 40 50 40 50
group restrained_atoms region restrain_region
fix position_restraint restrained_atoms spring/self 1.0 xyz
"""
_LAMMPS_FIXES[
    "minimise"
] = """
# ------ Energy minimise -----------------------
if "${rstID} >= 0" then "jump SELF end_minimise"
if "${minimise} == no && ${relax_cell} == no" then "jump SELF end_minimise"
    print "Doing CG minimise"
    if "${relax_cell} == yes" then "fix box all box/relax aniso 1.0 nreset 100"
    min_style cg
    min_modify line quadratic
    minimize ${etol} ${ftol} ${maxiter} ${maxiter}
    reset_timestep 0
label end_minimise
"""
_LAMMPS_FIXES[
    "plumed"
] = """
# ------ PLUMED ------------------------------------
if "${plumed} == no" then "jump SELF end_plumed"
    print "--- RUNNING PLUMED ---"
    fix plmd all plumed plumedfile ${plumed_infile} outfile plumed.out
label end_plumed
"""
_LAMMPS_FIXES[
    "ensemble"
] = """
# ------ Ensemble ----------------------------------
if "${deform} == yes" then "jump SELF end_ensemble"
# nve/nph
if "${ens} == nve"                  then "fix md all nve"
if "${ens} == nph"                  then "fix md all nph ${npttype} ${pres} ${pres} ${prel} pchain 5 mtk yes nreset 10000 drag ${pdrag}"
if "${ens} == nph || ${ens} == nve" then "jump SELF end_ensemble"
# Nose-Hoover
if "${ens} == nvt && ${tst} == nh"  then "fix tst all nvt temp ${tstart} ${tfinal} ${trel} tchain 5"
if "${ens} == npt && ${tst} == nh"  then "fix tst all npt temp ${tstart} ${tfinal} ${trel} ${npttype} ${pres} ${pres} ${prel} tchain 5 pchain 5 mtk yes nreset 10000 drag ${pdrag}"
# Other thermostats
if "${ens} == nvt && ${tst} != nh"  then "fix md all nve"
if "${ens} == npt && ${tst} != nh"  then "fix md all nph ${npttype} ${pres} ${pres} ${prel} pchain 5 mtk yes nreset 10000 drag ${pdrag}"
if "${tst} == ber"                  then "fix tst all temp/berendsen ${tstart} ${tfinal} ${trel}"
if "${tst} == lang"                 then "fix tst all langevin ${tstart} ${tfinal} ${trel} ${i1} tally yes zero yes"
if "${tst} == csvr"                 then "fix tst all temp/csvr ${tstart} ${tfinal} ${trel} ${i1}"
label end_ensemble

# ------ Time step ---------------------------------
timestep ${timestep}

# ------ Initial velocities and COM motion ---------
if "${rstID} < 0" then "velocity all create ${tstart} ${i0} mom yes dist gaussian"
fix com all momentum 1000 linear 1 1 1
"""
_LAMMPS_FIXES[
    "thermo_output"
] = """
# ------ Use target pressure for the Enthalpy ------
variable pv2h equal  1602191.7 # for metal units
variable enth equal  etotal+${pres}*vol/${pv2h}

# ------ Thermodynamic output ----------------------
variable str_basic string 'step time pe temp'
variable str_end string 'cpu cpuremain'
if "${ens} == nve" then "variable str_ens string 'etotal press'"
if "${ens} == nvt" then "variable str_ens string 'press'"
if "${ens} == npt || ${ens} == nph" then &
    "variable str_ens string 'vol density v_enth pxx pyy pzz pxy pxz pyz cella cellb cellc cellalpha cellbeta cellgamma'"
if "${deform} == yes" then &
    "variable str_ens string 'pxx pyy pzz pxy pxz pyz cella cellb cellc cellalpha cellbeta cellgamma xy xz yz'"
thermo_style custom ${str_basic} ${str_ens} ${str_end}
thermo ${nthermo}
thermo_modify flush yes
"""
_LAMMPS_FIXES[
    "dump"
] = """
# ------ Periodic Checkpoint -----------------------
restart 100000 checkpoint.1 checkpoint.2

# ------ Trajectory output -------------------------
if "${ntraj} <= 0 || ${ntraj} > ${nsteps} || ${nsteps} == 0" then "jump SELF end_dump"
    dump traj all ${trajType} ${ntraj} ${traj_file}.${trajType}
    dump_modify traj unwrap yes
label end_dump
"""
_LAMMPS_FIXES[
    "single"
] = """
# ------ Single point energy -----------------------
if "${single} == no" then "jump SELF end_single"
    variable e2body    equal ebond+evdwl
    variable ecoul_tot equal ecoul+elong
    variable str_dbg string 'pe ebond eangle edihed eimp evdwl ecoul elong etail v_e2body v_ecoul_tot'
    thermo_style custom ${str_dbg}
    run 0
    quit
label end_single
"""
_LAMMPS_FIXES[
    "md"
] = """
# ------ Molecular Dynamics ------------------------
if "${md} == no && ${plumed} == no" then "jump SELF end_md"
    run ${nsteps}
    if "${nsteps} > 0" then "write_restart ${new_restart}"
    quit
label end_md
"""
_LAMMPS_FIXES[
    "deform"
] = """
# ------ Cell deform -------------------------------
if "${deform} == no" then "jump SELF deform"

    if "${nequil} > 0 && ${tstart} != ${tfinal}" then &
        "fix md_equil all npt temp ${tstart} ${tfinal} ${trel} aniso ${pres} ${pres} ${prel} tchain 5 pchain 5 mtk yes" &
        "run ${nequil}" &
    if "${nequil} > 0" then &
        "fix md_equil all npt temp ${tfinal} ${tfinal} ${trel} aniso ${pres} ${pres} ${prel} tchain 5 pchain 5 mtk yes" &
        "run ${nequil}" &
        "unfix md_equil"

    if "${ens} == npt && ${def_dir} == x"  then &
        "fix md all nph y ${pres} ${pres} ${prel} z ${pres} ${pres} ${prel} pchain 5 mtk yes nreset 10000" &

    if "${ens} == npt && ${def_dir} == y"  then &
        "fix md all nph x ${pres} ${pres} ${prel} z ${pres} ${pres} ${prel} pchain 5 mtk yes nreset 10000"

    if "${ens} == npt && ${def_dir} == z"  then &
        "fix md all nph x ${pres} ${pres} ${prel} y ${pres} ${pres} ${prel} pchain 5 mtk yes nreset 10000"

    if "${ens} == nvt" then "fix md all nve"

    if "${tst} == csvr" then "fix tst all temp/csvr ${tstart} ${tfinal} ${trel} ${i1}"
    if "${tst} == lang" then "fix tst all langevin ${tstart} ${tfinal} ${trel} ${i1} tally yes zero yes"
    if "${tst} == ber"  then "fix tst all temp/berendsen ${tstart} ${tfinal} ${trel}"

    if "${def_dir} == x"  then &
        "variable tmp equal lx" &
        "variable L0 equal ${tmp}" &
        "variable stress equal -pxx" &
        "variable strain equal '(lx-v_L0)/v_L0'"
    if "${def_dir} == y"  then &
        "variable tmp equal ly" &
        "variable L0 equal ${tmp}" &
        "variable stress equal -pyy" &
        "variable strain equal '(ly-v_L0)/v_L0'"
    if "${def_dir} == z"  then &
        "variable tmp equal lz" &
        "variable L0 equal ${tmp}" &
        "variable stress equal -pzz" &
        "variable strain equal '(lz-v_L0)/v_L0'"

    thermo_style custom ${str_basic} ${str_ens} v_stress v_strain ${str_end}
    thermo ${nthermo}
    thermo_modify flush yes

    fix def all deform ${def_nsteps} ${def_dir} erate ${def_rate}
    run ${nsteps}
    write_restart ${new_restart}
    quit
label deform
"""

##############################################################################################################
_LAMMPS_FIXES[
    "ti"
] = """
# ------ Thermodynamic integration -----------------
if "${ti} == no" then "variable nt equal ${nsteps}" "jump SELF end_ti"

    if "${tst} == lang" then "unfix tst"
    fix ti all ti/spring ${ti_kappa} ${nsteps} ${nequil} function ${ti_function}
    if "${tst} == lang" then &
        "fix tst all langevin ${tstart} ${tfinal} ${trel} ${i1} tally yes zero yes"

    variable str_fix string  "f_ti[1] f_ti[2] f_ti"
    variable nt equal 2*(${nsteps}+${nequil})
    thermo_style custom ${str_basic} ${str_ens} ${str_fix} ${str_end}
    thermo ${nthermo}
    thermo_modify flush yes
    run ${nt}
    quit
label end_ti
"""
_LAMMPS_FIXES[
    "fep"
] = """
# ------ Free Energy Perturbation ------------------
if "${fep} == no" then "jump SELF end_fep"
    print "--- RUNNING FEP ---"
    kspace_modify gewald ${gewald}
#   uncomment to restraint atoms
#   group tiAtoms id 2 3
#   fix harm tiAtoms spring/self 1.5 xyz
    include ${fep_file}
    thermo_style custom ${str_basic} ${str_ens} ${str_end}
    thermo ${nthermo}
    thermo_modify flush yes
    run ${nequil}
    variable str_fix string "${str_fix}
    run ${nsteps}
    quit
label end_fep
"""


def replace_lammps_variables_in_string(content, replacements):
    """Replace values (4th column) of selected variables in a LAMMPS input string with aligned
    formatting.

    content : str or list of str
        LAMMPS input file content as a string or a list of lines.
        Dictionary where keys are variable names and values are the new values to set.

        modified_content : str
            The modified LAMMPS input content with replaced variable values and aligned formatting.
        replaced_count : int
            The number of variables that were replaced.

    Raises
    ------
    ValueError
        If content is not a string or a list of lines.

    Notes
    -----
    - Only lines starting with 'variable' and using the 'index' type are considered for replacement.
    - The function preserves comments and aligns columns for readability.
    - Lines using 'equal' or 'string' types are ignored.
    """
    replaced_count = 0
    variable_lines = []

    if isinstance(content, str):
        lines = content.splitlines(keepends=True)
    elif isinstance(content, list):
        lines = content  # Assume content is already a list of lines
    else:
        msg = "Content must be a string or a list of lines."
        raise TypeError(msg)  # Raise error if content is of invalid type

    # First pass: collect all variable lines to determine optimal column widths
    for i, line in enumerate(lines):
        stripped_line = line.strip()

        if stripped_line.startswith("variable "):
            parts = stripped_line.split()
            if len(parts) >= 4 and parts[2] == "index":
                variable_lines.append(
                    {
                        "index": i,
                        "var_name": parts[1],
                        "var_type": parts[2],
                        "value": parts[3],
                        "comment": "",
                    }
                )

                # Extract comment if present
                if "#" in line:
                    comment_start = line.find("#", line.find(parts[3]))
                    if comment_start != -1:
                        variable_lines[-1]["comment"] = line[comment_start:].rstrip()

    # Calculate optimal column widths
    if variable_lines:
        max_name_len = max(len(vl["var_name"]) for vl in variable_lines)
        max_type_len = max(len(vl["var_type"]) for vl in variable_lines)
        max_value_len = max(
            len(str(replacements.get(vl["var_name"], vl["value"])))
            for vl in variable_lines
        )
        # Set minimum widths and add padding
        name_width = max(max_name_len + 2, 16)
        type_width = max(max_type_len + 2, 8)
        value_width = max(max_value_len + 2, 25)

    # Second pass: format and replace variable lines
    for i, line in enumerate(lines):
        stripped_line = line.strip()

        # Skip empty lines and comments
        if not stripped_line or stripped_line.startswith("#"):
            continue

        # Check if line starts with 'variable'
        if stripped_line.startswith("variable "):
            if "equal" in stripped_line or "string" in stripped_line:
                continue
            parts = stripped_line.split()

            # Ensure we have at least 4 parts: variable, name, index/equal, value
            if len(parts) >= 4:
                var_name = parts[1]
                var_type = parts[2]
                original_value = parts[3]

                # Use replacement value if available, otherwise keep original
                new_value = replacements.get(var_name, original_value)

                # Extract comment if present
                comment_part = ""
                if "#" in line:
                    comment_start = line.find("#", line.find(parts[3]))
                    if comment_start != -1:
                        comment_part = " " + line[comment_start:].rstrip()

                # Format the line with proper alignment
                formatted_line = (
                    f"variable {var_name:<{name_width}}"
                    f"{var_type:<{type_width}}"
                    f"{new_value:<{value_width}}"
                    f"{comment_part}\n"
                )
                lines[i] = formatted_line

                # Track replacements
                if var_name in replacements and original_value != new_value:
                    replaced_count += 1
                    print(f"Replaced {var_name}: {original_value} -> {new_value}")

    return "".join(lines), replaced_count


def replace_lammps_variables(input_file, output_file, replacements):
    """Replace values (4th column) of selected variables in a LAMMPS input file with aligned formatting.

    Parameters:
    -----------
    input_file : str
        Path to the input LAMMPS file
    output_file : str
        Path to the output LAMMPS file
    replacements : dict
        Dictionary where keys are variable names and values are the new values to set

    Returns:
    --------
    int
        Number of variables successfully replaced
    """
    try:
        with open(input_file, "r") as infile:
            content = infile.read()

        modified_content, replaced_count = replace_lammps_variables_in_string(
            content, replacements
        )

        with open(output_file, "w") as outfile:
            outfile.write(modified_content)

        print(f"\nSuccessfully processed file. {replaced_count} variables replaced.")
        #        print(f"Output written to: {output_file}")

        return replaced_count

    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.")
        return 0
    except Exception as e:
        print(f"Error processing file: {str(e)}")
        return 0


def parse_variable_assignment(var_string):
    """
    Parse variable assignment from command line argument.
    Supports both 'var:value' and 'var=value' formats.

    Parameters:
    -----------
    var_string : str
        Variable assignment string (e.g., 'runID:5' or 'md=no')

    Returns:
    --------
    tuple
        (variable_name, value) or None if parsing fails
    """
    # Try colon separator first
    if ":" in var_string:
        parts = var_string.split(":", 1)
        if len(parts) == 2:
            return parts[0].strip(), parts[1].strip()

    # Try equals separator
    if "=" in var_string:
        parts = var_string.split("=", 1)
        if len(parts) == 2:
            return parts[0].strip(), parts[1].strip()

    # Invalid format
    return None


def main():
    """Main function for command line interface."""
    parser = argparse.ArgumentParser(
        description="Replace variable values in LAMMPS input files with aligned formatting.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python lmpgen.py -o output.lmp -v runID:5 -v md=no                  # Use template
  python lmpgen.py -i input.lmp -o output.lmp -v runID:5 -v md=no     # Use input file
  python lmpgen.py -i input.lmp -o output.lmp -v runID:10 -v minimise=yes -v deform:yes
  python lmpgen.py --output modified.lmp --variable coord_file:new_coords.lmp  # Template with custom vars
        """,
    )

    parser.add_argument(
        "-i",
        "--input",
        help="Input LAMMPS file path (if not provided, uses built-in template)",
    )

    parser.add_argument("-o", "--output", required=True, help="Output LAMMPS file path")

    parser.add_argument(
        "-f", "--forcefield", default="wcco", help="Forcefield type (full or wcco)"
    )

    parser.add_argument(
        "--variable",
        "-v",
        action="append",
        dest="variables",
        help='Variable assignment in format "name:value" or "name=value". Can be used multiple times.',
    )
    parser.add_argument(
        "--method",
        "-m",
        # choices=_INPUT_METHODS.keys(),
        default="all",
        help="Simulation method to use (default: 'all')",
    )

    parser.add_argument(
        "--extras",
        "-e",
        help="Additional simulation method to use",
    )

    args = parser.parse_args()

    # Parse variable assignments
    replacements = {}
    if args.variables:
        for var_assignment in args.variables:
            result = parse_variable_assignment(var_assignment)
            if result:
                var_name, value = result
                replacements[var_name] = value
                print(f"Will replace {var_name} -> {value}")
            else:
                print(f"Error: Invalid variable assignment format: '{var_assignment}'")
                print("Use format 'variable_name:value' or 'variable_name=value'")
                sys.exit(1)

    # Determine input source
    if args.input:
        print(f"Processing file: {args.input}")
        try:
            with open(args.input, "r") as infile:
                content = infile.read()
        except FileNotFoundError:
            print(f"Error: Input file '{args.input}' not found.")
            sys.exit(1)
        except Exception as e:
            print(f"Error reading file: {str(e)}")
            sys.exit(1)
    else:
        print("Using built-in LAMMPS template")

        simulation_methods = set()
        for method in args.method.split(","):
            simulation_methods.update(_INPUT_METHODS[method])
        if args.forcefield == "wcco":
            simulation_methods.update({"atomic", "tersoff_wcco"})
        elif args.forcefield == "grace":
            simulation_methods.update({"atomic", "grace_wcco"})
        elif args.forcefield == "full":
            simulation_methods.update({"full"})
        else:
            simulation_methods.update({"atomic", "tersoff_wcco"})

        if args.extras:
            for extra in args.extras.split(","):
                simulation_methods.add(extra)

        content = ""
        for block in _LAMMPS_BLOCKS:
            for section in block:
                if section in simulation_methods:
                    print(section)
                    # print(block[section])
                    content += block[section]

    if args.method != "all":
        replacements[args.method] = "yes"

    if replacements:
        print("-" * 50)

    # Process the content
    try:
        modified_content, replaced_count = replace_lammps_variables_in_string(
            content,
            replacements,
        )

        # Write output file
        with open(args.output, "w") as outfile:
            outfile.write(modified_content)

        if replaced_count > 0:
            print("\nSuccessfully replaced {replaced_count} variable(s)")
        elif replacements:
            print("\nNo matching variables found to replace")
        else:
            print("\nTemplate written to {args.output} (no variables replaced)")

        print(f"Output written to: {args.output}")

    except Exception as e:
        print(f"Error processing content: {str(e)}")
        sys.exit(1)


# Example usage
if __name__ == "__main__":
    main()
